### ISSUE TITLE
NNUE eval

### ISSUE THREAD

**Issue by FireFather** [egormoroz/gm_bit#1]
Hi,
Congrats on what I consider to be a fine programming effort, and a great engine!

I took the liberty to add NNUE support...and further optimized the codebase following Clang/Resharper C++ guidelines.

https://github.com/FireFather/saturn

**Comment by egormoroz** [comment]
Hi,
Sorry for replying 2 years later. Thank you for the kind words!

Your fork greatly helped me find bugs in my own NNUE implementation! I would have gone mad without an ability to compare to a solid baseline like yours!
